In [1]:
# imports
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = np.loadtxt("data/ECGu.txt")  # Load the ECG data from the text file
print(data) # Print the ECG data
print(data.shape) # Print the number of rows and columns

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
(6500, 3)


In [3]:
ecg_mV = data * (1024 / 1000)  # µV -> mV
# ou plus simplement, si tu considères directement : 1 unité = 1.024 mV
ecg_mV = data * 1.024

FS = 1000  # Hz
n_samples = ecg_mV.shape[0]
time_s = np.arange(n_samples) / FS